import fs from 'node:fs';
import prettier from 'prettier';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { compileCatalog } from './locale-catalog.mjs';
const root = path.resolve(import.meta.dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const check = process.argv.includes('--check');
const sources = [
	'localization/common.json',
	...['catalog', 'template', 'dealer'].map((kind) => `localization/${kind}.reviewed.json`)
];
const common = JSON.parse(read(sources[0]));
const rows = sources.slice(1).flatMap((file) => JSON.parse(read(file)));
const { en, bg, sourceKeys, ambiguousAliases } = compileCatalog(common, rows);
const dealerRows = JSON.parse(read('localization/dealer.reviewed.json'));
const dealerSourceKeys = Object.fromEntries(dealerRows.map((row) => [row.source, row.key]));
const rawContent =
	'// Generated by scripts/build-locales.mjs; edit localization catalogs.\n' +
	Object.entries({ en, bg, sourceKeys, dealerSourceKeys, ambiguousAliases })
		.map(([name, value]) => `export const ${name} = ${JSON.stringify(value, null, 2)} as const;\n`)
		.join('');
const prettierOptions = await prettier.resolveConfig(root + '/src/lib/locale/catalog.ts');
const content = await prettier.format(rawContent, { ...prettierOptions, parser: 'typescript' });
const hash = (data) => createHash('sha256').update(data).digest('hex');
const rawManifest =
	JSON.stringify(
		{
			schemaVersion: 2,
			enabledLocales: ['en', 'bg'],
			messages: Object.keys(en).length,
			catalogSha256: hash(content),
			sources,
			sourceSha256: Object.fromEntries(sources.map((file) => [file, hash(read(file))])),
			policySha256: hash(read('src/lib/locale/policy.ts')),
			ambiguousAliases,
			aliasPolicy:
				'An exact authored source wins over translated aliases when unique; otherwise ambiguous aliases are excluded. Context-specific message keys remain authoritative.'
		},
		null,
		2
	) + '\n';
const manifest = await prettier.format(rawManifest, { ...prettierOptions, parser: 'json' });
for (const [file, data] of [
	['src/lib/locale/catalog.ts', content],
	['localization/generated-manifest.json', manifest]
]) {
	if (check) {
		if (read(file) !== data) throw Error('Generated locale drift: ' + file);
	} else fs.writeFileSync(path.join(root, file), data);
}
console.log(
	JSON.stringify({
		status: check ? 'checked' : 'generated',
		messages: Object.keys(en).length,
		aliases: Object.keys(sourceKeys).length,
		quarantinedAliases: ambiguousAliases.length
	})
);
